export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GOOGLE_SIGN_IN_REQUEST = "GOOGLE_SIGN_IN_REQUEST";
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_FAILURE = "GOOGLE_SIGN_IN_FAILURE";
export const EMAIL_SIGN_IN_REQUEST = "EMAIL_SIGN_IN_REQUEST";
export const EMAIL_SIGN_IN_SUCCESS = "EMAIL_SIGN_IN_SUCCESS";
export const EMAIL_SIGN_IN_FAILURE = "EMAIL_SIGN_IN_FAILURE";
